# Generated by Django 6.0.7 on 2026-08-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_tarif', models.CharField(choices=[('forfait', 'Forfait fixe'), ('horaire', 'Tarif horaire'), ('devis', 'Sur devis')], max_length=20)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delai_intervention', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
