# Generated by Django 6.0.7 on 2026-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ariary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée sur WhatsApp'), ('en_cours', 'En cours de traitement'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='envoyee', max_length=10)),
                ('message_whatsapp', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
