# Generated by Django 6.0.7 on 2026-08-28 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix_ariary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('badge', models.CharField(max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='produits.categorie')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.marque')),
            ],
        ),
    ]
